export default [
  {
    text: 'Afghanistan (+93)',
    value: '+93',
    flag: 'af',
    key: 'af',
  },
  {
    text: 'Aland Islands',
    value: '',
    flag: 'ax',
    key: 'ax',
  },
  {
    text: 'Albania (+355)',
    value: '+355',
    flag: 'al',
    key: 'al',
  },
  {
    text: 'Algeria (+213)',
    value: '+213',
    flag: 'dz',
    key: 'dz',
  },
  {
    text: 'American Samoa (+1 684)',
    value: '+1 684',
    flag: 'as',
    key: 'as',
  },
  {
    text: 'Andorra (+376)',
    value: '+376',
    flag: 'ad',
    key: 'ad',
  },
  {
    text: 'Angola (+244)',
    value: '+244',
    flag: 'ao',
    key: 'ao',
  },
  {
    text: 'Anguilla (+1 264)',
    value: '+1 264',
    flag: 'ai',
    key: 'ai',
  },
  {
    text: 'Antigua (+1268)',
    value: '+1268',
    flag: 'ag',
    key: 'ag',
  },
  {
    text: 'Argentina (+54)',
    value: '+54',
    flag: 'ar',
    key: 'ar',
  },
  {
    text: 'Armenia (+374)',
    value: '+374',
    flag: 'am',
    key: 'am',
  },
  {
    text: 'Aruba (+297)',
    value: '+297',
    flag: 'aw',
    key: 'aw',
  },
  {
    text: 'Australia (+61)',
    value: '+61',
    flag: 'au',
    key: 'au',
  },
  {
    text: 'Austria (+43)',
    value: '+43',
    flag: 'at',
    key: 'at',
  },
  {
    text: 'Azerbaijan (+994)',
    value: '+994',
    flag: 'az',
    key: 'az',
  },
  {
    text: 'Bahamas (+1 242)',
    value: '+1 242',
    flag: 'bs',
    key: 'bs',
  },
  {
    text: 'Bahrain (+973)',
    value: '+973',
    flag: 'bh',
    key: 'bh',
  },
  {
    text: 'Bangladesh (+880)',
    value: '+880',
    flag: 'bd',
    key: 'bd',
  },
  {
    text: 'Barbados (+1 246)',
    value: '+1 246',
    flag: 'bb',
    key: 'bb',
  },
  {
    text: 'Belarus (+375)',
    value: '+375',
    flag: 'by',
    key: 'by',
  },
  {
    text: 'Belgium (+32)',
    value: '+32',
    flag: 'be',
    key: 'be',
  },
  {
    text: 'Belize (+501)',
    value: '+501',
    flag: 'bz',
    key: 'bz',
  },
  {
    text: 'Benin (+229)',
    value: '+229',
    flag: 'bj',
    key: 'bj',
  },
  {
    text: 'Bermuda (+1 441)',
    value: '+1 441',
    flag: 'bm',
    key: 'bm',
  },
  {
    text: 'Bhutan (+975)',
    value: '+975',
    flag: 'bt',
    key: 'bt',
  },
  {
    text: 'Bolivia (+591)',
    value: '+591',
    flag: 'bo',
    key: 'bo',
  },
  {
    text: 'Bosnia (+387)',
    value: '+387',
    flag: 'ba',
    key: 'ba',
  },
  {
    text: 'Botswana (+267)',
    value: '+267',
    flag: 'bw',
    key: 'bw',
  },
  {
    text: 'Bouvet Island',
    value: '',
    flag: 'bv',
    key: 'bv',
  },
  {
    text: 'Brazil (+55)',
    value: '+55',
    flag: 'br',
    key: 'br',
  },
  {
    text: 'British Virgin Islands (+1 284)',
    value: '+1 284',
    flag: 'vg',
    key: 'vg',
  },
  {
    text: 'Brunei (+673)',
    value: '+673',
    flag: 'bn',
    key: 'bn',
  },
  {
    text: 'Bulgaria (+359)',
    value: '+359',
    flag: 'bg',
    key: 'bg',
  },
  {
    text: 'Burkina Faso (+226)',
    value: '+226',
    flag: 'bf',
    key: 'bf',
  },
  {
    text: 'Burma (+95)',
    value: '+95',
    flag: 'mm',
    key: 'mm',
  },
  {
    text: 'Burundi (+257)',
    value: '+257',
    flag: 'bi',
    key: 'bi',
  },
  {
    text: 'Caicos Islands (+1 649)',
    value: '+1 649',
    flag: 'tc',
    key: 'tc',
  },
  {
    text: 'Cambodia (+855)',
    value: '+855',
    flag: 'kh',
    key: 'kh',
  },
  {
    text: 'Cameroon (+237)',
    value: '+237',
    flag: 'cm',
    key: 'cm',
  },
  {
    text: 'Canada (+1)',
    value: '+1',
    flag: 'ca',
    key: 'ca',
  },
  {
    text: 'Cape Verde (+238)',
    value: '+238',
    flag: 'cv',
    key: 'cv',
  },
  {
    text: 'Cayman Islands (+ 345)',
    value: '+ 345',
    flag: 'ky',
    key: 'ky',
  },
  {
    text: 'Central African Republic (+236)',
    value: '+236',
    flag: 'cf',
    key: 'cf',
  },
  {
    text: 'Chad (+235)',
    value: '+235',
    flag: 'td',
    key: 'td',
  },
  {
    text: 'Chile (+56)',
    value: '+56',
    flag: 'cl',
    key: 'cl',
  },
  {
    text: 'China (+86)',
    value: '+86',
    flag: 'cn',
    key: 'cn',
  },
  {
    text: 'Christmas Island (+61)',
    value: '+61',
    flag: 'cx',
    key: 'cx',
  },
  {
    text: 'Cocos Islands (+61)',
    value: '+61',
    flag: 'cc',
    key: 'cc',
  },
  {
    text: 'Colombia (+57)',
    value: '+57',
    flag: 'co',
    key: 'co',
  },
  {
    text: 'Comoros (+269)',
    value: '+269',
    flag: 'km',
    key: 'km',
  },
  {
    text: 'Congo (+243)',
    value: '+243',
    flag: 'cd',
    key: 'cd',
  },
  {
    text: 'Congo Brazzaville (+242)',
    value: '+242',
    flag: 'cg',
    key: 'cg',
  },
  {
    text: 'Cook Islands (+682)',
    value: '+682',
    flag: 'ck',
    key: 'ck',
  },
  {
    text: 'Costa Rica (+506)',
    value: '+506',
    flag: 'cr',
    key: 'cr',
  },
  {
    text: 'Cote Divoire (+225)',
    value: '+225',
    flag: 'ci',
    key: 'ci',
  },
  {
    text: 'Croatia (+385)',
    value: '+385',
    flag: 'hr',
    key: 'hr',
  },
  {
    text: 'Cuba (+53)',
    value: '+53',
    flag: 'cu',
    key: 'cu',
  },
  {
    text: 'Cyprus (+537)',
    value: '+537',
    flag: 'cy',
    key: 'cy',
  },
  {
    text: 'Czech Republic (+420)',
    value: '+420',
    flag: 'cz',
    key: 'cz',
  },
  {
    text: 'Denmark (+45)',
    value: '+45',
    flag: 'dk',
    key: 'dk',
  },
  {
    text: 'Djibouti (+253)',
    value: '+253',
    flag: 'dj',
    key: 'dj',
  },
  {
    text: 'Dominica (+1 767)',
    value: '+1 767',
    flag: 'dm',
    key: 'dm',
  },
  {
    text: 'Dominican Republic (+1 849)',
    value: '+1 849',
    flag: 'do',
    key: 'do',
  },
  {
    text: 'Ecuador (+593)',
    value: '+593',
    flag: 'ec',
    key: 'ec',
  },
  {
    text: 'Egypt (+20)',
    value: '+20',
    flag: 'eg',
    key: 'eg',
  },
  {
    text: 'El Salvador (+503)',
    value: '+503',
    flag: 'sv',
    key: 'sv',
  },
  {
    text: 'Equatorial Guinea (+240)',
    value: '+240',
    flag: 'gq',
    key: 'gq',
  },
  {
    text: 'Eritrea (+291)',
    value: '+291',
    flag: 'er',
    key: 'er',
  },
  {
    text: 'Estonia (+372)',
    value: '+372',
    flag: 'ee',
    key: 'ee',
  },
  {
    text: 'Ethiopia (+251)',
    value: '+251',
    flag: 'et',
    key: 'et',
  },
  {
    text: 'Europeanunion',
    value: '',
    flag: 'eu',
    key: 'eu',
  },
  {
    text: 'Falkland Islands (+500)',
    value: '+500',
    flag: 'fk',
    key: 'fk',
  },
  {
    text: 'Faroe Islands (+298)',
    value: '+298',
    flag: 'fo',
    key: 'fo',
  },
  {
    text: 'Fiji (+679)',
    value: '+679',
    flag: 'fj',
    key: 'fj',
  },
  {
    text: 'Finland (+358)',
    value: '+358',
    flag: 'fi',
    key: 'fi',
  },
  {
    text: 'France (+33)',
    value: '+33',
    flag: 'fr',
    key: 'fr',
  },
  {
    text: 'French Guiana (+594)',
    value: '+594',
    flag: 'gf',
    key: 'gf',
  },
  {
    text: 'French Polynesia (+689)',
    value: '+689',
    flag: 'pf',
    key: 'pf',
  },
  {
    text: 'French Territories',
    value: '',
    flag: 'tf',
    key: 'tf',
  },
  {
    text: 'Gabon (+241)',
    value: '+241',
    flag: 'ga',
    key: 'ga',
  },
  {
    text: 'Gambia (+220)',
    value: '+220',
    flag: 'gm',
    key: 'gm',
  },
  {
    text: 'Georgia (+995)',
    value: '+995',
    flag: 'ge',
    key: 'ge',
  },
  {
    text: 'Germany (+49)',
    value: '+49',
    flag: 'de',
    key: 'de',
  },
  {
    text: 'Ghana (+233)',
    value: '+233',
    flag: 'gh',
    key: 'gh',
  },
  {
    text: 'Gibraltar (+350)',
    value: '+350',
    flag: 'gi',
    key: 'gi',
  },
  {
    text: 'Greece (+30)',
    value: '+30',
    flag: 'gr',
    key: 'gr',
  },
  {
    text: 'Greenland (+299)',
    value: '+299',
    flag: 'gl',
    key: 'gl',
  },
  {
    text: 'Grenada (+1 473)',
    value: '+1 473',
    flag: 'gd',
    key: 'gd',
  },
  {
    text: 'Guadeloupe (+590)',
    value: '+590',
    flag: 'gp',
    key: 'gp',
  },
  {
    text: 'Guam (+1 671)',
    value: '+1 671',
    flag: 'gu',
    key: 'gu',
  },
  {
    text: 'Guatemala (+502)',
    value: '+502',
    flag: 'gt',
    key: 'gt',
  },
  {
    text: 'Guinea (+224)',
    value: '+224',
    flag: 'gn',
    key: 'gn',
  },
  {
    text: 'Guinea-Bissau (+245)',
    value: '+245',
    flag: 'gw',
    key: 'gw',
  },
  {
    text: 'Guyana (+595)',
    value: '+595',
    flag: 'gy',
    key: 'gy',
  },
  {
    text: 'Haiti (+509)',
    value: '+509',
    flag: 'ht',
    key: 'ht',
  },
  {
    text: 'Heard Island',
    value: '',
    flag: 'hm',
    key: 'hm',
  },
  {
    text: 'Honduras (+504)',
    value: '+504',
    flag: 'hn',
    key: 'hn',
  },
  {
    text: 'Hong Kong (+852)',
    value: '+852',
    flag: 'hk',
    key: 'hk',
  },
  {
    text: 'Hungary (+36)',
    value: '+36',
    flag: 'hu',
    key: 'hu',
  },
  {
    text: 'Iceland (+354)',
    value: '+354',
    flag: 'is',
    key: 'is',
  },
  {
    text: 'India (+91)',
    value: '+91',
    flag: 'in',
    key: 'in',
  },
  {
    text: 'Indian Ocean Territory (+246)',
    value: '+246',
    flag: 'io',
    key: 'io',
  },
  {
    text: 'Indonesia (+62)',
    value: '+62',
    flag: 'id',
    key: 'id',
  },
  {
    text: 'Iran (+98)',
    value: '+98',
    flag: 'ir',
    key: 'ir',
  },
  {
    text: 'Iraq (+964)',
    value: '+964',
    flag: 'iq',
    key: 'iq',
  },
  {
    text: 'Ireland (+353)',
    value: '+353',
    flag: 'ie',
    key: 'ie',
  },
  {
    text: 'Israel (+972)',
    value: '+972',
    flag: 'il',
    key: 'il',
  },
  {
    text: 'Italy (+39)',
    value: '+39',
    flag: 'it',
    key: 'it',
  },
  {
    text: 'Jamaica (+1 876)',
    value: '+1 876',
    flag: 'jm',
    key: 'jm',
  },
  {
    text: 'Jan Mayen (+47)',
    value: '+47',
    flag: 'sj',
    key: 'sj',
  },
  {
    text: 'Japan (+81)',
    value: '+81',
    flag: 'jp',
    key: 'jp',
  },
  {
    text: 'Jordan (+962)',
    value: '+962',
    flag: 'jo',
    key: 'jo',
  },
  {
    text: 'Kazakhstan (+7 7)',
    value: '+7 7',
    flag: 'kz',
    key: 'kz',
  },
  {
    text: 'Kenya (+254)',
    value: '+254',
    flag: 'ke',
    key: 'ke',
  },
  {
    text: 'Kiribati (+686)',
    value: '+686',
    flag: 'ki',
    key: 'ki',
  },
  {
    text: 'Kuwait (+965)',
    value: '+965',
    flag: 'kw',
    key: 'kw',
  },
  {
    text: 'Kyrgyzstan (+996)',
    value: '+996',
    flag: 'kg',
    key: 'kg',
  },
  {
    text: 'Laos (+856)',
    value: '+856',
    flag: 'la',
    key: 'la',
  },
  {
    text: 'Latvia (+371)',
    value: '+371',
    flag: 'lv',
    key: 'lv',
  },
  {
    text: 'Lebanon (+961)',
    value: '+961',
    flag: 'lb',
    key: 'lb',
  },
  {
    text: 'Lesotho (+266)',
    value: '+266',
    flag: 'ls',
    key: 'ls',
  },
  {
    text: 'Liberia (+231)',
    value: '+231',
    flag: 'lr',
    key: 'lr',
  },
  {
    text: 'Libya (+218)',
    value: '+218',
    flag: 'ly',
    key: 'ly',
  },
  {
    text: 'Liechtenstein (+423)',
    value: '+423',
    flag: 'li',
    key: 'li',
  },
  {
    text: 'Lithuania (+370)',
    value: '+370',
    flag: 'lt',
    key: 'lt',
  },
  {
    text: 'Luxembourg (+352)',
    value: '+352',
    flag: 'lu',
    key: 'lu',
  },
  {
    text: 'Macau (+853)',
    value: '+853',
    flag: 'mo',
    key: 'mo',
  },
  {
    text: 'Macedonia (+389)',
    value: '+389',
    flag: 'mk',
    key: 'mk',
  },
  {
    text: 'Madagascar (+261)',
    value: '+261',
    flag: 'mg',
    key: 'mg',
  },
  {
    text: 'Malawi (+265)',
    value: '+265',
    flag: 'mw',
    key: 'mw',
  },
  {
    text: 'Malaysia (+60)',
    value: '+60',
    flag: 'my',
    key: 'my',
  },
  {
    text: 'Maldives (+960)',
    value: '+960',
    flag: 'mv',
    key: 'mv',
  },
  {
    text: 'Mali (+223)',
    value: '+223',
    flag: 'ml',
    key: 'ml',
  },
  {
    text: 'Malta (+356)',
    value: '+356',
    flag: 'mt',
    key: 'mt',
  },
  {
    text: 'Marshall Islands (+692)',
    value: '+692',
    flag: 'mh',
    key: 'mh',
  },
  {
    text: 'Martinique (+596)',
    value: '+596',
    flag: 'mq',
    key: 'mq',
  },
  {
    text: 'Mauritania (+222)',
    value: '+222',
    flag: 'mr',
    key: 'mr',
  },
  {
    text: 'Mauritius (+230)',
    value: '+230',
    flag: 'mu',
    key: 'mu',
  },
  {
    text: 'Mayotte (+262)',
    value: '+262',
    flag: 'yt',
    key: 'yt',
  },
  {
    text: 'Mexico (+52)',
    value: '+52',
    flag: 'mx',
    key: 'mx',
  },
  {
    text: 'Micronesia (+691)',
    value: '+691',
    flag: 'fm',
    key: 'fm',
  },
  {
    text: 'Moldova (+373)',
    value: '+373',
    flag: 'md',
    key: 'md',
  },
  {
    text: 'Monaco (+377)',
    value: '+377',
    flag: 'mc',
    key: 'mc',
  },
  {
    text: 'Mongolia (+976)',
    value: '+976',
    flag: 'mn',
    key: 'mn',
  },
  {
    text: 'Montenegro (+382)',
    value: '+382',
    flag: 'me',
    key: 'me',
  },
  {
    text: 'Montserrat (+1664)',
    value: '+1664',
    flag: 'ms',
    key: 'ms',
  },
  {
    text: 'Morocco (+212)',
    value: '+212',
    flag: 'ma',
    key: 'ma',
  },
  {
    text: 'Mozambique (+258)',
    value: '+258',
    flag: 'mz',
    key: 'mz',
  },
  {
    text: 'Namibia (+264)',
    value: '+264',
    flag: 'na',
    key: 'na',
  },
  {
    text: 'Nauru (+674)',
    value: '+674',
    flag: 'nr',
    key: 'nr',
  },
  {
    text: 'Nepal (+977)',
    value: '+977',
    flag: 'np',
    key: 'np',
  },
  {
    text: 'Netherlands (+31)',
    value: '+31',
    flag: 'nl',
    key: 'nl',
  },
  {
    text: 'Netherlandsantilles (+599)',
    value: '+599',
    flag: 'an',
    key: 'an',
  },
  {
    text: 'New Caledonia (+687)',
    value: '+687',
    flag: 'nc',
    key: 'nc',
  },
  {
    text: 'New Guinea (+675)',
    value: '+675',
    flag: 'pg',
    key: 'pg',
  },
  {
    text: 'New Zealand (+64)',
    value: '+64',
    flag: 'nz',
    key: 'nz',
  },
  {
    text: 'Nicaragua (+505)',
    value: '+505',
    flag: 'ni',
    key: 'ni',
  },
  {
    text: 'Niger (+227)',
    value: '+227',
    flag: 'ne',
    key: 'ne',
  },
  {
    text: 'Nigeria (+234)',
    value: '+234',
    flag: 'ng',
    key: 'ng',
  },
  {
    text: 'Niue (+683)',
    value: '+683',
    flag: 'nu',
    key: 'nu',
  },
  {
    text: 'Norfolk Island (+672)',
    value: '+672',
    flag: 'nf',
    key: 'nf',
  },
  {
    text: 'North Korea (+850)',
    value: '+850',
    flag: 'kp',
    key: 'kp',
  },
  {
    text: 'Northern Mariana Islands (+1 670)',
    value: '+1 670',
    flag: 'mp',
    key: 'mp',
  },
  {
    text: 'Norway (+47)',
    value: '+47',
    flag: 'no',
    key: 'no',
  },
  {
    text: 'Oman (+968)',
    value: '+968',
    flag: 'om',
    key: 'om',
  },
  {
    text: 'Pakistan (+92)',
    value: '+92',
    flag: 'pk',
    key: 'pk',
  },
  {
    text: 'Palau (+680)',
    value: '+680',
    flag: 'pw',
    key: 'pw',
  },
  {
    text: 'Palestine (+970)',
    value: '+970',
    flag: 'ps',
    key: 'ps',
  },
  {
    text: 'Panama (+507)',
    value: '+507',
    flag: 'pa',
    key: 'pa',
  },
  {
    text: 'Paraguay (+595)',
    value: '+595',
    flag: 'py',
    key: 'py',
  },
  {
    text: 'Peru (+51)',
    value: '+51',
    flag: 'pe',
    key: 'pe',
  },
  {
    text: 'Philippines (+63)',
    value: '+63',
    flag: 'ph',
    key: 'ph',
  },
  {
    text: 'Pitcairn Islands (+872)',
    value: '+872',
    flag: 'pn',
    key: 'pn',
  },
  {
    text: 'Poland (+48)',
    value: '+48',
    flag: 'pl',
    key: 'pl',
  },
  {
    text: 'Portugal (+351)',
    value: '+351',
    flag: 'pt',
    key: 'pt',
  },
  {
    text: 'Puerto Rico (+1 939)',
    value: '+1 939',
    flag: 'pr',
    key: 'pr',
  },
  {
    text: 'Qatar (+974)',
    value: '+974',
    flag: 'qa',
    key: 'qa',
  },
  {
    text: 'Reunion (+262)',
    value: '+262',
    flag: 're',
    key: 're',
  },
  {
    text: 'Romania (+40)',
    value: '+40',
    flag: 'ro',
    key: 'ro',
  },
  {
    text: 'Russia (+7)',
    value: '+7',
    flag: 'ru',
    key: 'ru',
  },
  {
    text: 'Rwanda (+250)',
    value: '+250',
    flag: 'rw',
    key: 'rw',
  },
  {
    text: 'Saint Helena (+290)',
    value: '+290',
    flag: 'sh',
    key: 'sh',
  },
  {
    text: 'Saint Kitts and Nevis (+1 869)',
    value: '+1 869',
    flag: 'kn',
    key: 'kn',
  },
  {
    text: 'Saint Lucia (+1 758)',
    value: '+1 758',
    flag: 'lc',
    key: 'lc',
  },
  {
    text: 'Saint Pierre (+508)',
    value: '+508',
    flag: 'pm',
    key: 'pm',
  },
  {
    text: 'Saint Vincent (+1 784)',
    value: '+1 784',
    flag: 'vc',
    key: 'vc',
  },
  {
    text: 'Samoa (+685)',
    value: '+685',
    flag: 'ws',
    key: 'ws',
  },
  {
    text: 'San Marino (+378)',
    value: '+378',
    flag: 'sm',
    key: 'sm',
  },
  {
    text: 'Sandwich Islands (+500)',
    value: '+500',
    flag: 'gs',
    key: 'gs',
  },
  {
    text: 'Sao Tome (+239)',
    value: '+239',
    flag: 'st',
    key: 'st',
  },
  {
    text: 'Saudi Arabia (+966)',
    value: '+966',
    flag: 'sa',
    key: 'sa',
  },
  {
    text: 'Scotland (+248)',
    value: '+248',
    flag: 'gb sct',
    key: 'gb sct',
  },
  {
    text: 'Senegal (+221)',
    value: '+221',
    flag: 'sn',
    key: 'sn',
  },
  {
    text: 'Serbia',
    value: '',
    flag: 'cs',
    key: 'cs',
  },
  {
    text: 'Serbia (+381)',
    value: '+381',
    flag: 'rs',
    key: 'rs',
  },
  {
    text: 'Seychelles (+248)',
    value: '+248',
    flag: 'sc',
    key: 'sc',
  },
  {
    text: 'Sierra Leone (+232)',
    value: '+232',
    flag: 'sl',
    key: 'sl',
  },
  {
    text: 'Singapore (+65)',
    value: '+65',
    flag: 'sg',
    key: 'sg',
  },
  {
    text: 'Slovakia (+421)',
    value: '+421',
    flag: 'sk',
    key: 'sk',
  },
  {
    text: 'Slovenia (+386)',
    value: '+386',
    flag: 'si',
    key: 'si',
  },
  {
    text: 'Solomon Islands (+677)',
    value: '+677',
    flag: 'sb',
    key: 'sb',
  },
  {
    text: 'Somalia (+252)',
    value: '+252',
    flag: 'so',
    key: 'so',
  },
  {
    text: 'South Africa (+27)',
    value: '+27',
    flag: 'za',
    key: 'za',
  },
  {
    text: 'South Korea (+82)',
    value: '+82',
    flag: 'kr',
    key: 'kr',
  },
  {
    text: 'Spain (+34)',
    value: '+34',
    flag: 'es',
    key: 'es',
  },
  {
    text: 'Sri Lanka (+94)',
    value: '+94',
    flag: 'lk',
    key: 'lk',
  },
  {
    text: 'Sudan (+249)',
    value: '+249',
    flag: 'sd',
    key: 'sd',
  },
  {
    text: 'Suriname (+597)',
    value: '+597',
    flag: 'sr',
    key: 'sr',
  },
  {
    text: 'Swaziland (+268)',
    value: '+268',
    flag: 'sz',
    key: 'sz',
  },
  {
    text: 'Sweden (+46)',
    value: '+46',
    flag: 'se',
    key: 'se',
  },
  {
    text: 'Switzerland (+41)',
    value: '+41',
    flag: 'ch',
    key: 'ch',
  },
  {
    text: 'Syria (+963)',
    value: '+963',
    flag: 'sy',
    key: 'sy',
  },
  {
    text: 'Taiwan (+886)',
    value: '+886',
    flag: 'tw',
    key: 'tw',
  },
  {
    text: 'Tajikistan (+992)',
    value: '+992',
    flag: 'tj',
    key: 'tj',
  },
  {
    text: 'Tanzania (+255)',
    value: '+255',
    flag: 'tz',
    key: 'tz',
  },
  {
    text: 'Thailand (+66)',
    value: '+66',
    flag: 'th',
    key: 'th',
  },
  {
    text: 'Timorleste (+670)',
    value: '+670',
    flag: 'tl',
    key: 'tl',
  },
  {
    text: 'Togo (+228)',
    value: '+228',
    flag: 'tg',
    key: 'tg',
  },
  {
    text: 'Tokelau (+690)',
    value: '+690',
    flag: 'tk',
    key: 'tk',
  },
  {
    text: 'Tonga (+676)',
    value: '+676',
    flag: 'to',
    key: 'to',
  },
  {
    text: 'Trinidad (+1 868)',
    value: '+1 868',
    flag: 'tt',
    key: 'tt',
  },
  {
    text: 'Tunisia (+216)',
    value: '+216',
    flag: 'tn',
    key: 'tn',
  },
  {
    text: 'Turkey (+90)',
    value: '+90',
    flag: 'tr',
    key: 'tr',
  },
  {
    text: 'Turkmenistan (+993)',
    value: '+993',
    flag: 'tm',
    key: 'tm',
  },
  {
    text: 'Tuvalu (+688)',
    value: '+688',
    flag: 'tv',
    key: 'tv',
  },
  {
    text: 'United Arab Emirates (+971)',
    value: '+971',
    flag: 'ae',
    key: 'ae',
  },
  {
    text: 'Uganda (+256)',
    value: '+256',
    flag: 'ug',
    key: 'ug',
  },
  {
    text: 'Ukraine (+380)',
    value: '+380',
    flag: 'ua',
    key: 'ua',
  },
  {
    text: 'United Kingdom (+44)',
    value: '+44',
    flag: 'gb',
    key: 'gb',
  },
  {
    text: 'United States (+1)',
    value: '+1',
    flag: 'us',
    key: 'us',
  },
  {
    text: 'Uruguay (+598)',
    value: '+598',
    flag: 'uy',
    key: 'uy',
  },
  {
    text: 'US Minor Islands',
    value: '',
    flag: 'um',
    key: 'um',
  },
  {
    text: 'US Virgin Islands (+1 340)',
    value: '+1 340',
    flag: 'vi',
    key: 'vi',
  },
  {
    text: 'Uzbekistan (+998)',
    value: '+998',
    flag: 'uz',
    key: 'uz',
  },
  {
    text: 'Vanuatu (+678)',
    value: '+678',
    flag: 'vu',
    key: 'vu',
  },
  {
    text: 'Vatican City (+379)',
    value: '+379',
    flag: 'va',
    key: 'va',
  },
  {
    text: 'Venezuela (+58)',
    value: '+58',
    flag: 've',
    key: 've',
  },
  {
    text: 'Vietnam (+84)',
    value: '+84',
    flag: 'vn',
    key: 'vn',
  },
  {
    text: 'Wales (+266)',
    value: '+266',
    flag: 'gb wls',
    key: 'gb wls',
  },
  {
    text: 'Wallis and Futuna (+681)',
    value: '+681',
    flag: 'wf',
    key: 'wf',
  },
  {
    text: 'Western Sahara',
    value: '',
    flag: 'eh',
    key: 'eh',
  },
  {
    text: 'Yemen (+967)',
    value: '+967',
    flag: 'ye',
    key: 'ye',
  },
  {
    text: 'Zambia (+260)',
    value: '+260',
    flag: 'zm',
    key: 'zm',
  },
  {
    text: 'Zimbabwe (+263)',
    value: '+263',
    flag: 'zw',
    key: 'zw',
  },
];
